version: "3.8"
services:
  nginx:
    build:
      "./nginx"
    container_name: 
      "nginx"
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
      - 443:443
    restart:
      "always"
  react-app:
    build:
      "./../docker-frontend"
    ports:
      - 3000:3000  
#    volumes:
#      - ./src:/var/www/html
#    depends_on:
#      - client