version: "3.8"
services:
  nginx:
    build:
      "./nginx"
    container_name: 
      "nginx"
#    volumes:
#      - src:/var/www/html
#      - ./src:/var/www/html
    ports:
      - 80:80
      - 443:443
    restart:
      "always"
  react-app:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      "./../boilerplate-docker-react-tailwind"
    volumes:
      - .:/app
#      - ./app:/app
#      - ./app:/node/app
    ports:
      - 3000:3000
